### ISSUE TITLE
Open API 3 spec?

### ISSUE THREAD

**Issue by aaiezza** [amamenko/owen-wilson-wow-api#8]
Such a fun API. Great work!
I would love an [Open API 3](https://swagger.io/specification/) specification yaml so I can really easily import this into Postman! I can already think of some great applications of this API for demoing Postman and Swagger actually.

**Comment by kanadgupta** [comment]
I created an OpenAPI definition in #9! And I created some API docs on ReadMe here: https://wow.readme.io
